### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by crismblog** [stevenbenner/pacfinder#2] opened 2022-03-03 09:29 UTC
`make[2]: Leaving directory '/home/cristian/.cache/paru/clone/pacfinder/src/pacfinder-1.0/test'
make  check-TESTS
make[2]: Entering directory '/home/cristian/.cache/paru/clone/pacfinder/src/pacfinder-1.0/test'
make[3]: Entering directory '/home/cristian/.cache/paru/clone/pacfinder/src/pacfinder-1.0/test'
FAIL: test_suite

Testsuite summary for PacFinder 1.0

 TOTAL: 1
 PASS:  0
 SKIP:  0
 XFAIL: 0
 FAIL:  1
 XPASS: 0
 ERROR: 0

See test/test-suite.log
Please report to https://github.com/stevenbenner/pacfinder/issues

make[3]: *** [Makefile:730: test-suite.log] Error 1
make[3]: Leaving directory '/home/cristian/.cache/paru/clone/pacfinder/src/pacfinder-1.0/test'
make[2]: *** [Makefile:838: check-TESTS] Error 2
make[2]: Leaving directory '/home/cristian/.cache/paru/clone/pacfinder/src/pacfinder-1.0/test'
make[1]: *** [Makefile:911: check-am] Error 2
make[1]: Leaving directory '/home/cristian/.cache/paru/clone/pacfinder/src/pacfinder-1.0/test'
make: *** [Makefile:400: check-recursive] Error 1
==> ERROR: A failure occurred in check().
    Aborting...
error: failed to build 'pacfinder-1.0-1':
error: packages failed to build: pacfinder-1.0-1`

**Comment by stevenbenner** [comment] 2022-03-03 13:37
Thank you for submitting the failure test report.

Is your system configured with a locale that uses commas for the decimal mark in numbers?

**Comment by stevenbenner** [comment] 2022-03-04 15:23
This issue was almost certainly a duplicate of issue #1. The fix for that was released with version 1.1.

I'm going to go ahead and close this issue as a duplicate. Please try out the latest version and see if it resolves the problem. If the problem persists then reply to this issue and I'll look into the problem again.

**Closed** 2022-03-04 15:23 UTC
Labels: duplicate
